wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721844736.0
    t:
      1:
      - 1
      - 35
      - 55
      2:
      - 1
      - 35
      - 55
      3:
      - 13
      - 23
      4: 3.11.8
      5: 0.16.5
      8:
      - 5
      13: linux-x86_64
