wandb_version: 1

num_net_channels:
  desc: null
  value: 512
num_net_in_channels:
  desc: null
  value: 1
net_dropout:
  desc: null
  value: 0.3
net_action_size:
  desc: null
  value: 14
num_simulations:
  desc: null
  value: 800
self_play_games:
  desc: null
  value: 1
num_iters:
  desc: null
  value: 1
epochs:
  desc: null
  value: 1600
lr:
  desc: null
  value: 1.2166489157239913e-05
max_buffer_size:
  desc: null
  value: 70000
num_pit_games:
  desc: null
  value: 40
random_pit_freq:
  desc: null
  value: 2
batch_size:
  desc: null
  value: 255
tau:
  desc: null
  value: 1
arena_tau:
  desc: null
  value: 0.01
c:
  desc: null
  value: 1
checkpoint_dir:
  desc: null
  value: C:\Users\Skyr\PycharmProjects\testMuAlphaZeroLib\Checkpoints
update_threshold:
  desc: null
  value: 0.6
num_workers:
  desc: null
  value: 1
log_epsilon:
  desc: null
  value: 1.0e-09
zero_tau_after:
  desc: null
  value: 5
az_net_linear_input_size:
  desc: null
  value:
  - 36
  - 72
  - 144
log_dir:
  desc: null
  value: C:\Users\Skyr\PycharmProjects\testMuAlphaZeroLib\Logs
pushbullet_token:
  desc: null
  value: null
num_blocks:
  desc: null
  value: 8
l2:
  desc: null
  value: 0.0001
eval_epochs:
  desc: null
  value: 50
net_latent_size:
  desc: null
  value:
  - 6
  - 6
support_size:
  desc: null
  value: 601
unravel:
  desc: null
  value: true
requires_player_to_reset:
  desc: null
  value: false
arena_running_muzero:
  desc: null
  value: false
use_wandb:
  desc: null
  value: false
num_net_out_channels:
  desc: null
  value: 256
rep_input_channels:
  desc: null
  value: 128
K:
  desc: null
  value: 5
gamma:
  desc: null
  value: 0.997
frame_buffer_size:
  desc: null
  value: 32
frame_skip:
  desc: null
  value: 4
num_steps:
  desc: null
  value: 10
c2:
  desc: null
  value: 19652
alpha:
  desc: null
  value: 0.8
beta:
  desc: null
  value: 1
pickle_dir:
  desc: null
  value: /home/skyr/PycharmProjects/testMuAlphaZeroLib/Data
target_resolution:
  desc: null
  value:
  - 96
  - 96
show_tqdm:
  desc: null
  value: false
resize_images:
  desc: null
  value: true
muzero:
  desc: null
  value: true
use_original:
  desc: null
  value: true
use_pooling:
  desc: null
  value: true
multiple_players:
  desc: null
  value: false
scale_state:
  desc: null
  value: true
balance_term:
  desc: null
  value: 1
enable_per:
  desc: null
  value: true
num_worker_iters:
  desc: null
  value: 100000
_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1720428170.0
    t:
      1:
      - 1
      - 35
      - 55
      3:
      - 16
      - 23
      4: 3.11.8
      5: 0.16.5
      8:
      - 5
      13: linux-x86_64
